version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
#      - '8888:80'
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/opt/work
  php:
    build: ./docker/php
    volumes:
      - .:/opt/work