version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
    depends_on:
      - php
      - api
    volumes:
      - .:/var/www
  php:
    build: ./docker/php
    volumes:
      - .:/var/www
    working_dir: /var/www
  api:
    image:
      sbgtechtest/api:latest
    ports:
      - "8888-8890:8888-8890"